### ISSUE TITLE
RBT_FILE_READ_ERROR

### ISSUE THREAD

**Issue by leticrisassis** [CBDD/rDock#106]
Hi,

I am having trouble running rDock. Immediately upon attempting to start it, I encounter the following error:
[1koc.log](https://github.com/CBDD/rDock/files/15118859/1koc.log)

I appreciate your attention to this matter, and any guidance you can provide to help resolve this issue would be greatly appreciated.

Best regards,
Letícia Cristina de Assis

**Comment by ggutierrez-sunbright** [comment]
Hi,

I'm sorry for the (very) late reply.
Probably you either figured it out or didn't want to keep trying/using rDock, but in the improbable chance you're still interested in finding out a solution to this issue, please let me know.  

Taking a look at the log, it seems to me it is trying to open a file that doesn't really exist (or the permissions are not allowing your user to read it):  
```~/Documents/benchmark_NAs/pdbbind_rDock/1koc/data/masses.rtf```

the `RBT_ROOT` environment variable is set to the `1koc` folder.  
Is it really where rDock is installed?  
I recently updated the [makefile](Makefile) and the installation instructions in the [readme](README.md), just in case it's of any help.  


Once more, I'm sorry for the delay.

Thanks for your patience, and best regards.


Guillermo

**Comment by leticrisassis** [comment]
Aqui está a resposta que você pode usar:
------------------------------

*Subject:* Successful rDock Docking Run

Hi Guillermo,

No worries about the delay. I really appreciate your response!

I wanted to let you know that I managed to successfully run docking with
rDock. After addressing the environment variable settings and ensuring all
required files were in the correct locations, everything worked smoothly.

Thank you for your suggestions, and for updating the makefile and
installation instructions in the readme – they were quite helpful!

If I encounter any additional issues or questions regarding rDock, I'll be
sure to reach out.

Best regards,
Letícia
------------------------------

Caso queira algum ajuste ou adição, é só avisar! 😊

Em seg., 16 de dez. de 2024 às 18:01, ggutierrez ***@***.***>
escreveu:
