### ISSUE TITLE
segmentation fault from RemoveNonPolarHydrogens() in ubuntu22 installation

### ISSUE THREAD

**Issue by AlvaroSmorras** [CBDD/rDock#11]
Hi,

I have installed rdock on ubuntu22 using gcc and g++ at 7.5 version. Everything seems to compile fine, passes the tests but when executing rbdock it gives a segmentation fault.
I re-compiled it on the debug mode and the errors appear always when dealing with the receptor mol2, when its time to remove non-polar hydrogens.  This error is consistent when trying it with many different systems, all that have worked in other compilations of rDock.

```
***********************************************
The rDock program is licensed under GNU-LGPLv3.0. http://rdock.sourceforge.net/
Executable:	rbdock ($Id: //depot/dev/client3/rdock/2021.1/src/exe/rbdock.cxx#4 $)
Library:	libRbtD.so/2021.1/901 2021/07/19
RBT_ROOT:	/opt/SOFT/rdock/2021.dev.2
RBT_HOME:	/home/aserrano

[...]

Trying to match HZ3
INFO Setting group charge on A1:LYS_160:HZ3 to 0.333

Trying to match OE1
INFO Setting group charge on A1:GLU_163:OE1 to -0.5

Trying to match OE2
INFO Setting group charge on A1:GLU_163:OE2 to -0.5
Removing bond #7 (CA-HA)
Segmentation fault (core dumped)
```

When given a mol2 with no non-polar hydrogens, the execution is able to move forward to reading the ligands and crashes when performing the same operation with the ligands.

```
***********************************************
The rDock program is licensed under GNU-LGPLv3.0. http://rdock.sourceforge.net/
Executable:	rbdock ($Id: //depot/dev/client3/rdock/2021.1/src/exe/rbdock.cxx#4 $)
Library:	libRbtD.so/2021.1/901 2021/07/19
RBT_ROOT:	/opt/SOFT/rdock/2021.dev.2
RBT_HOME:	/home/aserrano

[...]

 11 21  1  0  0  0  0
 11 22  1  0  0  0  0
M  END
>  <_MOLCOUNT>
1

>  <DISTR[pH=7]>
94.96

>  <TAUTOMER_DISTRIBUTION>
100


**************************************************
RECORD #1
Removing bond #2 (C1-H13)
Segmentation fault (core dumped)
```

I believe that the functions failing are the following, any help pointing towards what can be happening would be greatly appreciated 

https://github.com/CBDD/rDock/blob/e920f627d5806f6bda75bc0f76d96f2c1e30c4a5/src/lib/RbtMOL2FileSource.cxx#L520-L542
https://github.com/CBDD/rDock/blob/e920f627d5806f6bda75bc0f76d96f2c1e30c4a5/src/lib/RbtPsfFileSource.cxx#L323-L342
https://github.com/CBDD/rDock/blob/e920f627d5806f6bda75bc0f76d96f2c1e30c4a5/src/lib/RbtMdlFileSource.cxx#L1019-L1044

**Comment by ggutierrez-sunbright** [comment]
Hi @AlvaroSmorras,
I've tracked down the issue, and it seems to happen here:
https://github.com/CBDD/rDock/blob/e920f627d5806f6bda75bc0f76d96f2c1e30c4a5/src/lib/RbtBaseMolecularFileSource.cxx#L257-L276

the segfault comes from the combination of `erase` at line 274 and the `mapIter++` at line 263
