### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by debanjansen48** [CBDD/rDock#2]
From mailing list I came to know the use of conda to install rDOCk
I created a new env and successfully installed rDOCk

I downloaded the validation set files and try to run rDOCK, but it returns the following error

(rdock) debanjan@debanjan:~/Downloads/rDock_2013.1_src/tutorial/RNA_rDock_TestSet/1aju$ rbcavity -r 1aju_rdock.prm -was > 1aju_cavity.log
/home/debanjan/miniconda3/envs/rdock/bin/rbcavity: line 7:  **3883 Segmentation fault      (core dumped) "$RBT_ROOT/bin/$PROGNAME" "$@**

**Comment by sruizcarmona** [comment]
That's a conda related issue, and it's independent from our github development. 
I recommend you to try what I suggested on the other issue you opened, with the new available dev branch:
https://github.com/CBDD/rDock/tree/dev-2021
