### ISSUE TITLE
why patches

### ISSUE THREAD

**Issue by pschmidtke** [CBDD/rDock#4]
@sruizcarmona why are you preparing patches to be deployed, rather than changing the codebase itself & releasing a new updated release?

Just wondered on how you see this ongoing

**Comment by sruizcarmona** [comment]
Yes, you are right, it's quite confusing sorry.

I was playing around with some changes offline and kept the patches as I was moving around the code testing different things in different computers and wanted to quickly access what I was changing.
They were finally included in the code and then pushed to the dev-2021 branch, so could be effectively removed without change.

**Comment by pschmidtke** [comment]
ok so the branch already contains applied patches, right?

**Comment by sruizcarmona** [comment]
yes, correct! Just ignore all the *.patch files as they have already been applied.

**Comment by pschmidtke** [comment]
I also have issues with the makefile vs Makefile. 

which one is it? can we drop one ? :)

**Comment by sruizcarmona** [comment]
both are currently being used at some point. I guess it could be fixed of course, so feel free to clean it up if you have the time!
