### ISSUE TITLE
could we expose the makefile generation procedure as well in the doc ?

### ISSUE THREAD

**Issue by pschmidtke** [CBDD/rDock#5]
I noticed the make.log:

that's very valuable if you want to generate the code for other platforms as well - should we expose that in the readme or as build script at least?

-> sort of linked to the makefile vs Makefile thing (which creates weird issues on my mac when pulling the repo)

**Comment by ggutierrez-sunbright** [comment]
Hi @pschmidtke,
The old build system has been deprecated as of issue #15 . It's still accessible but no longer maintained.

I'm closing this issue as stale

Regards

Guillermo
