### ISSUE TITLE
macOS installation

### ISSUE THREAD

**Issue by alyferryhalo** [CBDD/rDock#54]
Hello!

I tried to install rDock via `conda install -c bioconda rdock` but it didn't work. Moreover, for installation guide, only Lunix was mentioned. Is there a way to install rDock on macOS?

**Comment by ggutierrez-sunbright** [comment]
Hi!

bioconda version of rdock is not up to date, and i'm not sure about it being compatible with osx, but you should be able to compile rdock on your own, if you have the dependencies installed.

you will need a c++ compiler, like gcc/g++ or clang, make, and libpopt (for this one, maybe running `brew install popt` would suffice, but i'm not 100% sure)

then clone/download the repository, open a terminal on the repository folder, and run
```
CXX=clang make test
```

(assuming you're using clang as c++ compiler)

this will build the rdock library, all the executables (rbdock, rbcavity, etc), and check rdock returns the expected results.

if this command runs successfully, then you are ready to install and use it

there's more detailed information on the [readme](README.md) about the compilation process. the ubuntu specific part is only for the required dependencies


please let us know if you find any issue while compiling the project

regards,

guillermo
