### ISSUE TITLE
I tried to make but it failed

### ISSUE THREAD

**Issue by ProzacR** [CBDD/rDock#7]
Here error:
$ make linux-g++-64
make "PLATFORM=linux-g++-64" "CONFIG=release" "VERSION=rDock-main.0" -f Makefile rdock
make[1]: Entering directory '/mnt/c/Vyto/rDock-main/build'
make[1]: *** No rule to make target 'rdock'.  Stop.
make[1]: Leaving directory '/mnt/c/Vyto/rDock-main/build'
make: *** [makefile:73: linux-g++-64] Error 2

Hopefully helpful.

**Comment by ggutierrez-sunbright** [comment]
Hi @ProzacR,
The old build system has been deprecated (issue #15)
Please, give the new one a try, and create a new ticket if build is still failing.

Thanks and regards

Guillermo
