### ISSUE TITLE
sdrmsd file has mixed spaces and tabs. Refuses to execute

### ISSUE THREAD

**Issue by stefdoerr** [CBDD/rDock#9]
I cannot figure out the intended indentation without trying to understand the script though.
For example here but there are many more spots: https://github.com/CBDD/rDock/blob/main/bin/sdrmsd#L215-L217

**Comment by ggutierrez-sunbright** [comment]
Hi Stefan,

we're working right now on migrating all utility scripts to python3 (from python2 and perl both)

please subscribe to #59 for more updates on this effort specifically, or #55 for the general migration

regards

guillermo
